# Generated by Django 4.2.6 on 2023-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=90)),
                ('taskdesc', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
